add page for adding/removing questions for a list
3PillarGlobal-Czechia/interview-app-ui pull request #12
Opened 2022-03-04 09:36 UTC by TomasNiemczyk98

## Summary

Added a page for adding/removing questions for a list

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactoring (non-breaking change to code and structure)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-03-07 13:03 UTC, michal-rozehnal commented on src/components/QuestionList.tsx
> +    title: ColumnTitle<InterviewQuestionModel>;
I would recommend move into separate type definition. When everything is here it is hard to read where definition and body are defined.

2022-03-08 08:32 UTC, VHolan requested changes

2022-03-09 13:50 UTC, TomasNiemczyk98 commented on src/utils/tableUtils.tsx
> +export function createColumnSearchProps(
this is a method mainly because it is returning an object not a jsx, if needed we can discuss

2022-03-11 06:55 UTC, VHolan commented on src/App.tsx
> +        <RouterComponent />
I would get rid of Component suffix.

2022-03-11 06:56 UTC, VHolan commented on src/components/Header.module.scss
> +    >:nth-child(1) {
rather use `last-child` and `first-child`

2022-03-11 07:01 UTC, VHolan commented on src/components/QuestionListData.tsx
> +    <div className={styles.questionListsData}>
I would switch condition and keep rendering of tables at the bottom of function.

2022-03-11 07:04 UTC, VHolan commented on src/components/QuestionLists.module.scss
> +.black {
Rename class to element where is used. `.black` class sounds for me as global css and not for certain component.

2022-03-11 07:04 UTC, VHolan commented on src/components/QuestionLists.module.scss
> +.black {
Rename all the occurrences.

2022-03-11 07:06 UTC, VHolan commented on src/components/RouterComponent.tsx
> +export default function RouterComponent(): JSX.Element {
Check docs/FOLDER_STRUCTURE.MD. You should move router to to own file in root of src folder

2022-03-11 07:09 UTC, VHolan commented
Please check documentation of FOLDER_STRUCTURE. Feel free to call me and discuss it.

2022-03-14 08:46 UTC, TerezaSkutova commented on src/components/QuestionListData.tsx
> +          a.difficulty != null && b.difficulty != null
It is not necessary to compare an object with null value, you can write this condition easier.
`a.difficulty && b.difficulty`

2022-03-15 15:30 UTC, michal-rozehnal commented on src/components/TableWrapper.tsx
> +  dataSource: RecordType[];
I recommend move definition of props into separate file. It's hard to read code now.

2022-03-15 15:30 UTC, michal-rozehnal commented on .eslintrc.json
> +    "no-param-reassign": ["warn"],
Best practice is discuss any rule turn-off with team. If you did that than this comment is irrelevant.

2022-03-15 15:30 UTC, michal-rozehnal commented on src/domain/QuestionList/QuestionCart.tsx
> +  isVisible: boolean;
I recommend move definition of props into separate file. It's hard to read code now.

2022-03-15 15:30 UTC, michal-rozehnal commented on src/domain/QuestionList/QuestionListData.tsx
> +  isBeingEdited: boolean;
I recommend move definition of props into separate file. It's hard to read code now.

2022-03-15 15:30 UTC, michal-rozehnal commented on src/domain/QuestionList/QuestionListData.tsx
> +          'title',
I would keep this values in some constants or enum.

2022-03-15 15:30 UTC, michal-rozehnal commented on src/domain/QuestionList/QuestionListHeader.tsx
> +  isBeingEdited: boolean;
I recommend move definition of props into separate file. It's hard to read code now.

2022-03-15 15:30 UTC, michal-rozehnal commented on src/services/table/FilterDropdown.tsx
> +  dataIndex: string;
I recommend move definition of props into separate file. It's hard to read code now.

2022-03-15 15:30 UTC, michal-rozehnal commented on src/services/table/tableUtils.tsx
> +  title: ColumnTitle<InterviewQuestionModel>;
I recommend move definition of props into separate file. It's hard to read code now.

2022-03-15 19:23 UTC, michal-rozehnal approved these changes

2022-03-15 19:49 UTC, merged