26 doc update documentation for UI setup and development
3PillarGlobal-Czechia/interview-app-ui pull request #29
Opened 2022-03-28 10:53 UTC by PlesnikJakub

## Summary

Documentation enhancement covering contributing, API client, and UI design.

Any fixes or recommendations are welcome. ❤️ 

## Types of changes

- [x] Documentation
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactoring (non-breaking change to code and structure)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Testing

N/A

## Notes

N/A

2022-03-29 07:14 UTC, petrspelos requested changes
I'd say let's apply at least the `spelling/grammar` suggestions.

- I believe applying the `doc-link` suggestions could preemptively answer the simplest of questions
- The SimpleLogin `optional/suggestion` is certainly something to perhaps discuss

---

Other than that, we've got a set of docs any open source repo can envy us. ☺️ 🎉

2022-03-29 07:14 UTC, petrspelos commented on README.md
> +- Make sure API is running on url specified in .env file
`doc-link`, `spelling/grammar`

```suggestion
- Make sure [the API](https://github.com/3PillarGlobal-Czechia/interview-app-api) is running on the URL specified in the `.env` file
```

2022-03-29 07:14 UTC, petrspelos commented on README.md
> +- Make sure API is running on url specified in .env file
`question`

@PlesnikJakub, do you think we should explain how to create and structure the `.env` file?

Or at least what the environment variable name is for the API endpoint? 🤔

2022-03-29 07:14 UTC, petrspelos commented on README.md
> +`npm lint` - Runs eslint with quiet and autofix flag \
`doc-link`

```suggestion
`npm lint` - Runs [ESLint](https://eslint.org/) with the quiet and autofix flags \
```

2022-03-29 07:14 UTC, petrspelos commented on docs/API_CLIENT.md
> +Auto-generation is done through the package NSwag which uses open API documentation to generate typescript client code. NSwag is listed as a dev dependency in this project.
`doc-link`

```suggestion
Auto-generation is done through the [NSwag package](https://openbase.com/js/nswag/documentation) which uses the open API documentation to generate typescript client code. NSwag is listed as a dev dependency in this project. 

```

2022-03-29 07:14 UTC, petrspelos commented on docs/API_CLIENT.md
> +After any changes in the contract on API (new endpoints, URL changes, requests, or return types) ApiClinet needs to be regenerated to reflect all changes.
`spelling/grammar`

```suggestion
After any changes to the API contract (new endpoints, URL changes, requests, or return types) ApiClient needs to be regenerated to reflect these changes. 

```

2022-03-29 07:14 UTC, petrspelos commented on docs/DESIGN.md
> +The application design is based on UI Toolkit [Ant Design](https://ant.design/) with some custom elements designed specificaly for purposes of this application. The main focus of our design is to mak
`spelling/grammar`

```suggestion
The application design is based the [Ant Design](https://ant.design/) UI Toolkit with some custom elements designed specifically for the purposes of this application. The main focus of our design is to make the application lightweight, features easily accessible and fast to use.

```

2022-03-29 10:17 UTC, PlesnikJakub commented on README.md
> +Welcome to UI repository of Interview app. Goal of this project is to create a tool that can help technical interviewes to lead an interview with a increased confidence and ability to stay consistent
No

2022-03-29 10:36 UTC, PlesnikJakub commented
I guess I should start marking PRs as drafts to avoid the wall of shame like this 😅

2022-03-29 10:39 UTC, petrspelos commented
> I guess I should start marking PRs as drafts to avoid the wall of shame like this 😅

There's no shame in healthy collaboration, @PlesnikJakub. ❤️ #oneteam

2022-03-29 10:45 UTC, PlesnikJakub commented on CONTRIBUTING.md
> +Contact authors directly via email.
We may consider this in the future but for now, I think we are fine. 
Feel free to log this as an issue 😊

2022-03-30 08:16 UTC, petrspelos approved these changes

2022-03-30 11:04 UTC, merged