Refactor/question set detail page
3PillarGlobal-Czechia/interview-app-ui pull request #41
Opened 2022-04-06 12:37 UTC by TomasNiemczyk98

## Summary

1st iteration of question set detail page, some stuff is slightly off, something is not working, but hopefully a step in the right direction

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Refactoring (non-breaking change to code and structure)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

https://user-images.githubusercontent.com/92929243/161975710-bc353fd2-402a-4946-bed1-04d77b4eef58.mp4

2022-04-08 12:09 UTC, petrspelos commented
@TomasNiemczyk98 while the circle buttons currently have the incorrect color, the ones with a checkbox in them should have a dashed type. This is something AntDesign gives us for free. You think we could use that?

```
 <Button type="dashed" shape="circle" ... />
```

2022-04-08 12:50 UTC, TomasNiemczyk98 commented
> @TomasNiemczyk98 while the circle buttons currently have the incorrect color, the ones with a checkbox in them should have a dashed type. This is something AntDesign gives us for free. You think we could use that?
> 
> ```
>  <Button type="dashed" shape="circle" ... />
> ```

My bad I did not even realize that AntDesign's buttons can be customized in this way, I will change implementation according to this

2022-04-11 09:14 UTC, PlesnikJakub requested changes
There is a couple of small comments that prevent this to be merged.

@TomasNiemczyk98 please let me know if you have the capacity for the requested changes. We will take over if you won't be able to make it.

2022-04-11 09:14 UTC, PlesnikJakub commented on src/domain/QuestionList/QuestionSetView.tsx
> +              ).toFixed(2)
I think it's not ideal to compute the average difficulty in this place.  I propose we rework this to a separate function that will take an array of questions and returns average difficulty. That would create one place responsible for such logic and with future changes to the difficulty attribute (already planned), we will have a more resilient solution. 

Regarding where should be such function stored, I would not hesitate to put it into some sort of service.

2022-04-11 09:14 UTC, PlesnikJakub commented on src/services/arrayUtils.ts
> +export function arrayDistinct<T>(arr: T[]): T[] {
Not sure is this is **service** or just a **helper** 🤔

2022-04-11 09:14 UTC, PlesnikJakub commented on src/services/arrayUtils.ts
> +export function arrayDistinct<T>(arr: T[]): T[] {
I see we have multiple utils inside the service folder, we should probably consider what is the correct location.

2022-04-13 07:15 UTC, PlesnikJakub approved these changes
Thank you for your contribution and resolution of our comments, I think this PR is in good enough shape to be merged now 🚀

2022-04-13 07:18 UTC, merged